### ISSUE TITLE
Center Stage Page View

### ISSUE THREAD

**Issue by dokastho** [dokastho/Homepage#3]
# Center Stage Page View

## Description
Pages need their own independent views for rendering the site. Given that they're rendered using react, it might be necessary to have them "blow up" on the index page instead of routing to a new page altogether. This enhancement does not include app-specific widgets

## Components
- Thumbnail
- Page

## TODO

- [ ] Prevent scrolling & background interaction
- [ ] Overall design
- [ ] ~~Page Attributes~~
- [ ] Make REST API return object of thumbnails instead of list. This will make random access easier when clicking and ordering thumbnails
- [ ] Set height of center-stage card independent of current scrolled height

## Notes

- Integrated Page component

## Changelog
- Page ID's now generated randomly. When a thumbnail was created, the index had no way of knowing what the new thumbnail's ID was without a request to the REST API. By generating them randomly, we avoid this issue and allow the react side to pick the `pageId`.
